### ISSUE TITLE
"Run Forge Events" option has inverted functionality

### ISSUE THREAD

**Issue by elwooha6** [ezterry/ezwasteland#2]
Title pretty much says it all. When using CoFH Core to generate ores the "Run Forge Events" option in world customization actually disables the ore gen when enabled and vice versa.

Minecraft: 1.10.2
Mod Version: 1.10.2-1.0
Forge Version: 12.18.3.2254

**Comment by ezterry** [comment]
This was tested when I provided instructions on curse with the following customization string:

S:CustomizationJson={"terrainvariation":{"amplification":22,"variation":2},"randopts":{"oceans":false,"globaloffset":-5,**"integration":true**,"villages":true,"villagechance":49.295773,"strongholds":true},"domes":{"lgmincount":3,"lgmaxcount":8,"lgradius":39,"lgheight":4,"midmincount":2,"midmaxcount":8,"midradius":16,"midheight":5,"smmincount":2,"smmaxcount":4,"smradius":10,"smheight":4},"shallows":{"mincount":3,"maxcount":8,"radius":44,"depth":4},"spire":{"count":2,"size":3}}

The terrain generator stops the forge event onChunkPopulate (included in forge for vanilla terrain) when the integration (Run forge events in gui) is set true we call this event for other mods to add relevant decoration to the world.  When its not set this event is not called.

I've verified the code and that with the proper configuration everything seems to work, between ezWastelands and CoFH core, testing on a new world.  That said I do not know what hooks and tweaks CoFH is using thus I'm unsure if the integration flag is required for all or any of the customization that mod is adding.
