### ISSUE TITLE
Port to 1.13.2 forge with wasteland meteors

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [ezterry/ezwasteland#4]
Any chance

**Comment by ezterry** [comment]
Highly unlikely, forge took too long on 1.13 and I don't have much time or interest to play that version of Minecraft currently .. if many mods are released I may reconsider but I suspect most large ones will skip 1.13 because 1.14 will be out before they stabilize

**Comment by CrankySupertoonArchive** [comment]
What if i port it myself

**Comment by ezterry** [comment]
The license of this project [2 clause BSD] was deliberately picked.  Allowing fairly free access to the source, without asking me, and with a clause to say you are mostly on your own.

Of course if you add an interesting feature into the base mod I'd be interested (if provided under the terms of the same BSD license) in a patch for future versions as I do intend to port this forward to forge 1.14.* and continue the fabric port.  (I admit infinite time I might make the stepping stone version to 1.13, however  my day job has way too much coding, and sometimes I need to play a games too)
