### ISSUE TITLE
Will this mod be developed anymore?

### ISSUE THREAD

**Issue by kanpov** [ezterry/ezwasteland#8]
There haven't been any commits to this repo since 2019 (it's almost 2022 at the time of writing this) + the current MC version is 1.18, while the mod runs on snapshot 1.14.

@ezterry Can I make an updated fork of this project for 1.18?

**Comment by ezterry** [comment]
Regarding any forks: please follow the project's licence (2 clause bad). Also it's appreciated to use githubs fork functionality, and or provided a link back here.

Distribution the same terms apply, however on curseforge I would expect a link back to the current curseforge project clearly indicating it's a fork.

A pull request with the changes is appreciated in case I revive this project, but I'm not actively working on it.  (This may change but life is busy and I'm not sure what's my vision of wastelands should be in 1.18+ )
